### ISSUE TITLE
邀请您共同建设Study-In-Bjtu项目

### ISSUE THREAD

**Issue by Rbrq03** [paulzhn/bjtu-bachelor-thesis#3]
学长您好

我是北京交通大学计算机学院21级的本科生,  我们观察到目前在北京交通大学latex/markdown等语言的普及度仍然较低, 一部分原因是因为官方没有给出一个合适的latex/markdown作业/ppt模版, 我们希望能建设一个这样的库一来便利同学们使用latex/markdown学习工作, 二来推广在北交latex/markdown, 我们目前已经建立了一个Study-In-Bjtu库https://github.com/Rbrq03/Study-In-BJTU, 同时发现了您撰写的高质量beamer模版 因此希望能邀请您共同建设Study-In-Bjtu项目 (目前希望能集成您的latex 毕业论文库 后续希望能一起开发更多的模版)。 我们期望在这个项目后期能和老师以及官方（本科生院和研究生院）一起合作推广这个库 , 不知道能否和您后续交流 我的微信是Rbrq03
 
祝您学习工作以及生活一切顺利

**Comment by paulzhn** [comment]
可以，注明credit即可

**Comment by Rbrq03** [comment]
非常感谢
